"""Release node — ensure branch is pushed, generate PR description."""

from __future__ import annotations

import logging
from typing import Any

from hadron.config.defaults import BRANCH_PREFIX
from hadron.models.events import EventType, PipelineEvent
from hadron.models.pipeline_state import PipelineState
from hadron.pipeline.nodes import NodeContext, RepoInfo, pipeline_node

logger = logging.getLogger(__name__)


def _join_criteria(criteria: list[str]) -> str:
    return "\n".join(f"- {c}" for c in criteria)


@pipeline_node("release")
async def release_node(state: PipelineState, ctx: NodeContext, cr_id: str) -> dict[str, Any]:
    """Ensure branch is pushed and generate PR description summary."""
    wm = ctx.worktree_manager
    structured_cr = state.get("structured_cr", {})
    ri = RepoInfo.from_state(state)

    # Ensure branch is pushed
    try:
        await wm.commit_and_push(ri.worktree_path, f"chore: release push for {cr_id}")
    except RuntimeError as e:
        logger.debug("Release push for %s: %s", ri.repo_name, e)

    # Generate PR description
    pr_body = f"""## AI-Generated: {structured_cr.get('title', cr_id)}

### Change Request
{structured_cr.get('description', 'N/A')}

### Acceptance Criteria
{_join_criteria(structured_cr.get('acceptance_criteria', []))}

### Pipeline Summary
- **CR ID:** {cr_id}
- **Dev iterations:** {state.get('dev_loop_count', 0)}
- **Review iterations:** {state.get('review_loop_count', 0)}
- **Estimated cost:** ${state.get('cost_usd', 0):.4f}

### Review Findings
"""
    for rr in state.get("review_results", []):
        if rr.get("repo_name") == ri.repo_name:
            if rr.get("findings"):
                for f in rr["findings"]:
                    pr_body += f"- [{f.get('severity', '')}] {f.get('message', '')}\n"
            else:
                pr_body += "No issues found.\n"

    pr_body += "\n---\nGenerated by Hadron AI Pipeline"

    release_results = [{
        "repo_name": ri.repo_name,
        "branch": f"{BRANCH_PREFIX}{cr_id}",
        "pr_description": pr_body,
    }]

    await ctx.event_bus.emit(PipelineEvent(
        cr_id=cr_id, event_type=EventType.STAGE_COMPLETED, stage="release",
        data={"repos": [r["repo_name"] for r in release_results]},
    ))

    return {
        "release_results": release_results,
        "current_stage": "release",
        "stage_history": [{"stage": "release", "status": "completed"}],
    }
