"""Release node — ensure branch is pushed, generate PR description."""

from __future__ import annotations

import logging
from typing import Any

from hadron.config.defaults import BRANCH_PREFIX
from hadron.git.github import GitHubAPIError, create_pull_request
from hadron.git.url import extract_owner_repo
from hadron.models.events import EventType, PipelineEvent
from hadron.models.pipeline_state import PipelineState
from hadron.pipeline.nodes import NodeContext, RepoInfo, pipeline_node
from hadron.pipeline.nodes.cr_format import format_criteria

logger = logging.getLogger(__name__)


@pipeline_node("release")
async def release_node(state: PipelineState, ctx: NodeContext, cr_id: str) -> dict[str, Any]:
    """Ensure branch is pushed and generate PR description summary."""
    wm = ctx.worktree_manager
    structured_cr = state.get("structured_cr", {})
    ri = RepoInfo.from_state(state)

    # Ensure branch is pushed
    try:
        await wm.commit_and_push(ri.worktree_path, f"chore: release push for {cr_id}")
    except RuntimeError as e:
        logger.debug("Release push for %s: %s", ri.repo_name, e)

    # Generate PR description
    pr_body = f"""## AI-Generated: {structured_cr.get('title', cr_id)}

### Change Request
{structured_cr.get('description', 'N/A')}

### Acceptance Criteria
{format_criteria(structured_cr.get('acceptance_criteria', []))}

### Pipeline Summary
- **CR ID:** {cr_id}
- **Dev iterations:** {state.get('dev_loop_count', 0)}
- **Review iterations:** {state.get('review_loop_count', 0)}
- **Estimated cost:** ${state.get('cost_usd', 0):.4f}

### Review Findings
"""
    for rr in state.get("review_results", []):
        if rr.get("repo_name") == ri.repo_name:
            if rr.get("findings"):
                for f in rr["findings"]:
                    pr_body += f"- [{f.get('severity', '')}] {f.get('message', '')}\n"
            else:
                pr_body += "No issues found.\n"

    pr_body += "\n---\nGenerated by Hadron AI Pipeline"

    # Create PR on GitHub
    branch = f"{BRANCH_PREFIX}{cr_id}"
    pr_url = ""
    try:
        owner, repo_short = extract_owner_repo(state["repo"]["repo_url"])
        pr_result = await create_pull_request(
            owner=owner,
            repo=repo_short,
            head=branch,
            base=ri.default_branch,
            title=structured_cr.get("title", cr_id),
            body=pr_body,
        )
        pr_url = str(pr_result["html_url"])
        logger.info("Created PR %s for %s", pr_url, ri.repo_name)
    except (GitHubAPIError, ValueError, KeyError) as e:
        logger.warning("PR creation failed for %s: %s", ri.repo_name, e)

    release_results = [{
        "repo_name": ri.repo_name,
        "branch": branch,
        "pr_url": pr_url,
        "pr_description": pr_body,
    }]

    await ctx.event_bus.emit(PipelineEvent(
        cr_id=cr_id, event_type=EventType.STAGE_COMPLETED, stage="release",
        data={"repos": [r["repo_name"] for r in release_results]},
    ))

    return {
        "release_results": release_results,
        "current_stage": "release",
        "stage_history": [{"stage": "release", "status": "completed"}],
    }
