"""Release node — ensure branch is pushed, generate PR description."""

from __future__ import annotations

from langgraph.types import RunnableConfig

import logging
from typing import Any

from hadron.config.defaults import BRANCH_PREFIX
from hadron.git.worktree import WorktreeManager
from hadron.models.events import EventType, PipelineEvent
from hadron.models.pipeline_state import PipelineState
from hadron.pipeline.nodes import NodeContext

logger = logging.getLogger(__name__)


async def release_node(state: PipelineState, config: RunnableConfig) -> dict[str, Any]:
    """Ensure branch is pushed and generate PR description summary."""
    ctx = NodeContext.from_config(config)
    cr_id = state["cr_id"]

    await ctx.event_bus.emit(PipelineEvent(
            cr_id=cr_id, event_type=EventType.STAGE_ENTERED, stage="release"
        ))

    wm = WorktreeManager(ctx.workspace_dir)
    structured_cr = state.get("structured_cr", {})

    repo = state.get("repo", {})
    repo_name = repo.get("repo_name", "")
    worktree_path = repo.get("worktree_path", "")

    # Ensure branch is pushed
    try:
        await wm.commit_and_push(worktree_path, f"chore: release push for {cr_id}")
    except RuntimeError:
        pass  # May have nothing new to push

    # Generate PR description
    pr_body = f"""## AI-Generated: {structured_cr.get('title', cr_id)}

### Change Request
{structured_cr.get('description', 'N/A')}

### Acceptance Criteria
{chr(10).join(f'- {c}' for c in structured_cr.get('acceptance_criteria', []))}

### Pipeline Summary
- **CR ID:** {cr_id}
- **Dev iterations:** {state.get('dev_loop_count', 0)}
- **Review iterations:** {state.get('review_loop_count', 0)}
- **Estimated cost:** ${state.get('cost_usd', 0):.4f}

### Review Findings
"""
    for rr in state.get("review_results", []):
        if rr.get("repo_name") == repo_name:
            if rr.get("findings"):
                for f in rr["findings"]:
                    pr_body += f"- [{f.get('severity', '')}] {f.get('message', '')}\n"
            else:
                pr_body += "No issues found.\n"

    pr_body += "\n---\nGenerated by Hadron AI Pipeline"

    release_results = [{
        "repo_name": repo_name,
        "branch": f"{BRANCH_PREFIX}{cr_id}",
        "pr_description": pr_body,
    }]

    await ctx.event_bus.emit(PipelineEvent(
            cr_id=cr_id, event_type=EventType.STAGE_COMPLETED, stage="release",
            data={"repos": [r["repo_name"] for r in release_results]},
        ))

    return {
        "release_results": release_results,
        "current_stage": "release",
        "stage_history": [{"stage": "release", "status": "completed"}],
    }
